name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm --prefix ./frontend install
      - run: npm --prefix ./frontend run build
      - run: touch .env
      - run: echo NODE_ENV=${{ vars.NODE_ENV}} >> .env
      - run: echo PORT=${{ vars.PORT}} >> .env
      - run: echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
      - run: echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
      - run: cat .env
      - run: pm2 stop mern-auth
      - run: pm2 start mern-auth
      - run: pm2 save
      - run: sudo service nginx restart
